config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  get '/posts/new', to: 'posts#new'
  post '/posts', to: 'posts#create'
  get '/posts/:id', to: 'posts#show', as: :post
  get '/posts/:id/upvote', to: 'posts#upvote', as: :upvote
  get '/posts/:id/downvote', to: 'posts#downvote', as: :downvote
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments, dependent: :destroy
    after_initialize :set_defaults

    def set_defaults
        if self.upvotes.nil?
            self.upvotes = 0
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def index 
        @posts = Post.all 
    end

    def new
        @post = Post.new
    end

    def create
        @post = Post.new(params.require(:post).permit(:title, :content))

        if @post.save
            redirect_to root_path
        else
            render :new
        end
    end

    def show
        @post = Post.find(params[:id])
    end

    def upvote
        @post = Post.find(params[:id])
        @post.upvotes += 1
        @post.save
        redirect_to post_path(@post)
    end

    def downvote
        @post = Post.find(params[:id])
        @post.downvotes += 1
        @post.save
        redirect_to post_path(@post)
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogio</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/hack/0.8.1/hack.css' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/hack/0.8.1/standard.css' %>
  </head>

  <body>
    <div class"containter">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Blogio's Bloggy Blog</h1>

<%= link_to "New Post", posts_new_path %>

<center>
<h2>All Posts</h2>
</center>

<table>
    <tbody>
    <tr>
        <th>Post Title</th>
        <th>Upvotes</th>
        <th>Date Published</th>
    </tr>
    <% @posts.each do |post| %>
        <tr>
            <td><%= link_to post.title, post_path(post) %></td>
            <td><%= post.upvotes %></td>
            <td><%= post.created_at %></td>
        </tr>
    <% end %>
    </tbody>
</table>

app/views/posts/new.html.erb
<center>
<h1>New Posty Post</h1>


<%= form_for @post do |f| %>

    <%= f.label :title %>
    <%= f.text_field :title %>


    <%= f.label :content %>
    <%= f.text_area :content %>

    <%= f.submit %>

<% end %>
</center>

app/views/posts/show.html.erb
<%= link_to "All Posts", root_path %>
<%= link_to "New Posts", posts_new_path %>

<h3><%= @post.title %></h3>

<%= @post.content %>

<%= link_to "Upvote", upvote_path(@post) %>
<%= link_to "Downvote", downvote_path(@post) %>